config/routes.rb
Rails.application.routes.draw do
  
  root to: "static_pages#index" #para pagina inicial
  
  resources :despesas
  
  resources :agendamentos do
    get :todos, on: :collection
    get :futuros, on: :collection
    get :json_teste, on: :collection
  end
  
  resources :servicos do
    get :caixa_total, on: :collection #usar collection pra trazer lista de dados
    get :servicos_do_dia, on: :collection
  end

  resources :relatorios do
    get :servicos, on: :collection
    get :despesas, on: :collection
    get :lucro_mes, on: :collection
  end

  get 'users/json_teste', to: 'users#json_teste'
  get '/financeiro', to: 'static_pages#financeiro'

  resources :users, only: [:new, :create, :index]

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy', as: 'sair'


  
  resources :caixas
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :require_logged_in_user

	def index
		@nome = "Wiron"
		@servicos = Servico.all
    	@valor_total = @servicos.map(&:valor).map(&:to_f).sum
		@servicos_do_dia = Servico.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'")
    	@valor_total_dia = @servicos_do_dia.map(&:valor).map(&:to_f).sum

		@despesas = Despesa.all
		@despesas_valor = @despesas.map(&:valor).map(&:to_f).sum
		@despesas_do_dia = @despesas.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'").sum(:valor_real)
	
		@valor_total_lucro = @valor_total - @despesas_valor

		@agendamentos = Agendamento.all
		@qnt_agendamentos_dia = @agendamentos.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'").count
		@qnt_agendamentos_futuros = @agendamentos.where("to_char(data,'YYYY-MM-DD') > '#{Time.now.to_date.to_s}'").count
		
		
	end

	def financeiro
		
		@servicos = Servico.all
		@despesas = Despesa.all
		@servicos_mes = @servicos.where(data: Time.now.beginning_of_month..Time.now.end_of_month)
		@servicos_mes_count = @servicos_mes.count
		

		@despesas_mes = @despesas.where(data: Time.now.beginning_of_month..Time.now.end_of_month)
		@servicos_mes_valor = @servicos_mes.map(&:valor).map(&:to_f).sum
		@despesas_mes_valor = @despesas_mes.sum(&:valor_real)
		@lucro_mes = @servicos_mes_valor - @despesas_mes_valor

#binding.pry

		@servicos_mes_ticket = @servicos_mes_valor / @servicos_mes_count unless @servicos_mes_count == 0

		if params[:data_search].present?
			@mes = params[:data_search]
			ano = @mes.split("-")[0].to_i
			mes = @mes.split("-")[1].to_i
			@servicos_mes = @servicos.where("DATE_PART('year', data) = ? AND DATE_PART('month', data) = ?", ano, mes)
			@despesas_mes = @despesas.where("DATE_PART('year', data) = ? AND DATE_PART('month', data) = ?", ano, mes)
			@servicos_mes_valor = @servicos_mes.map(&:valor).map(&:to_f).sum
			@despesas_mes_valor = @despesas_mes.sum(&:valor_real)
			@lucro_mes = @servicos_mes_valor - @despesas_mes_valor
			@servicos_mes_count = @servicos_mes.count

			if @servicos_mes_count == 0
				@servicos_mes_ticket = 0
			else
				@servicos_mes_ticket = @servicos_mes_valor / @servicos_mes_count
			end 



		end
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/financeiro.html.erb
<style>
@media print {
 .no-print{
	display: none !important;
 }

 .show-print{
	display: block !important;
 }

 .reset-css-print{
	border: none !important;
	box-shadow: 0px 0px 0px !important;
 }
}

li .active {
	background-color: #572057 !important;
}

 .nav-item button:not(.active){
	color: #000 !important
}
</style>

<h2 class="mt-2">Relatório Financeiro</h2>

<form>
<div class="row no-print">
 <div class="col-sm-2 mb-2">
		<input type="month" name="data_search" value="<%= params[:data_search].present? ? params[:data_search] : Time.now.strftime('%Y-%m') %>" class="form-control" >
	</div>
	<div class="col-sm-3">
		<button type="submit" class="btn bg-roxo text-white ms-3">Buscar</button>
		<a href="/financeiro" class="btn bg-roxo text-white ms-2">Limpar Filtro</a>
	</div>
	<div class="col-sm-7">
		<a href="#" class="btn bg-roxo text-white ms-2 float-end" id="imprimir_financeiro">Imprimir</a>
	</div>
</div>
</form>

<div class="p-2 mt-4 card shadow reset-css-print">
	<ul class="nav nav-pills mb-3 mt-4" id="pills-tab" role="tablist">
		<li class="nav-item" role="presentation">
			<button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Serviços</button>
		</li>
		<li class="nav-item" role="presentation">
			<button class="nav-link" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Despesas</button>
		</li>
		<li class="nav-item" role="presentation">
			<button class="nav-link" id="pills-profile-tab2" data-bs-toggle="pill" data-bs-target="#pills-profile2" type="button" role="tab" aria-controls="pills-profile2" aria-selected="false">Serviços + Despesas</button>
		</li>
	</ul>
	<div class="tab-content" id="pills-tabContent">
		<div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
			<table class="table">
				<thead>
					<tr>
						<th >Data</th>
						<th >Nome cliente</th>
						<th >Servico</th>
						<th class="text-end">Valor</th>
										
					</tr>
				</thead>

				<tbody>
					<% @servicos_mes.each do |servico| %>
						<tr>
							<td><div><b class="ocultar-res">Data</b> <div><%= servico.data.strftime('%d/%m/%Y') %></div></div></td>
							<td><div><b class="ocultar-res">Cliente</b> <div><%= servico.nome_cliente.upcase %></div></div></td>
							<td><div><b class="ocultar-res">Serviço</b> <div><%= servico.servico.upcase.gsub(/\-.+/, "") %></div></div></td>
							<td><div class="text-end"><b class="ocultar-res">Valor</b> <div><%= numero_real(servico.valor,2) %></div></div></td>
							
							
						</tr>
					<% end %>
						<tr>
							<td colspan=4 class="text-end">
								<div><strong>Ticket médio</strong> <%=  numero_real(@servicos_mes_ticket,2) %></div>
								<strong>Total</strong> <%= numero_real(@servicos_mes_valor,2) %>
							</td>
						</tr>
				</tbody>
			</table>
		</div>
		<div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
			<table class="table">
					<thead>
						<tr>
							<th >Data</th>
							<th >Observação</th>
							<th class="text-end">Valor</th>
											
						</tr>
					</thead>

					<tbody>
						<% @despesas_mes.each do |despesa| %>
							<tr>
								<td><div><b class="ocultar-res">Data</b> <div><%= despesa.data.strftime('%d/%m/%Y') %></div></div></td>
								<td><div><b class="ocultar-res">Cliente</b> <div><%= despesa.descricao.upcase %></div></div></td>
								<td class="text-end"><div><b class="ocultar-res">Valor</b> <div><%= numero_real(despesa.valor_real,2) %></div></div></td>
								
								<td class="border-botton ocultar-res"></td>
							</tr>
						<% end %>
							<tr>
								<td colspan="2" class="text-end" >&nbsp;</td>
								<td  class="text-end"><strong>Total</strong><br> <%= numero_real(@despesas_mes_valor,2) %></td>
							</tr>
					</tbody>
				</table>
		</div>
		<div class="tab-pane fade" id="pills-profile2" role="tabpanel" aria-labelledby="pills-profile-tab2" tabindex="0">
			<table class="table">
				<thead>
					<tr>
						<th >Data</th>
						<th >Nome cliente</th>
						<th >Servico</th>
						<th class="text-end">Valor</th>
										
					</tr>
				</thead>

				<tbody>
					<% @servicos_mes.each do |servico| %>
						<tr>
							<td><div><b class="ocultar-res">Data</b> <div><%= servico.data.strftime('%d/%m/%Y') %></div></div></td>
							<td><div><b class="ocultar-res">Cliente</b> <div><%= servico.nome_cliente.upcase %></div></div></td>
							<td><div><b class="ocultar-res">Serviço</b> <div><%= servico.servico.upcase.gsub(/\-.+/, "") %></div></div></td>
							<td class="text-end"><div><b class="ocultar-res">Valor</b> <div><%= numero_real(servico.valor,2) %></div></div></td>
							
							<td class="border-botton ocultar-res"></td>
						</tr>
					<% end %>
						<tr>
							
							<td colspan=4 class="text-end">
								<div><strong>Serviços</strong> <%= numero_real(@servicos_mes_valor,2) %></div>
								<div class="text-danger"><strong>Despesas</strong> <%= numero_real(@despesas_mes_valor,2) %></div>
								<div><strong>Total</strong> <%= numero_real(@lucro_mes,2) %></div>
							</td>
						</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>


<div class="hide show-print mt-5 text-center" style="font-size: 0.8rem">
	Relatório impresso <%= Date.today.strftime("%d/%m/%Y")%> por <%= maiusculo(current_user.nome) %> às <span id="hora-print"></span>
</div>

<script>
$('#imprimir_financeiro').click(function(){
		hora = $('#hora-print')
		now = new Date;
		hora.html(now.getHours() + ":" + now.getMinutes() + ":" + now.getSeconds())
    window.print();
    return false;
})
</script>
  

app/views/static_pages/index.html.erb
	<div class="mt-2">
		
		<div class="mt-5 text-center">
			<div class="mt-1 text-white badge text-wrap" style="text-decoration: none; font-size: 1.5rem; width: 15rem; height: 3rem; background-color: #572057 !important">
				<i class="bi bi-coin float-start"></i><%= link_to 'Caixa diário', servicos_do_dia_servicos_path, class:'text-white', style:'text-decoration: none;' %>
			</div>
		</div>

		<div class="mt-3 text-center ">
      <div class="mt-1 text-white badge text-wrap" style="text-decoration: none; font-size: 1.5rem; width: 15rem; height: 3rem; background-color: #572057 !important">
				<i class="bi bi-scissors float-start"></i><%= link_to 'Serviços', servicos_path, class:'text-white', style:'text-decoration: none;' %>
			</div>
		</div>

		<div class="mt-3 text-center <%= @qnt_agendamentos_dia > 0 ? 'animate__animated animate__headShake' : '' %>">
      <div class="mt-1 text-white badge text-wrap position-relative" style="text-decoration: none; font-size: 1.4rem; width: 15rem; height: 3rem; background-color: #572057 !important">			
				<i class="bi bi-filter float-start fs-2"></i>
				<%= link_to 'Agendamentos', agendamentos_path, class:'text-white', style:'text-decoration: none;' %>
				<% if @qnt_agendamentos_dia > 0 %>
					<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger ">
						<%= @qnt_agendamentos_dia %>
					</span>		
				<% end %>		
			</div>
		</div>

		<div class="mt-3 text-center">
      <div class="mt-1 text-white badge text-wrap" style="text-decoration: none; font-size: 1.5rem; width: 15rem; height: 3rem; background-color: #572057 !important">
				<i class="bi bi-graph-down-arrow float-start"></i><%= link_to 'Despesas', despesas_path, class:'text-white', style:'text-decoration: none;' %>
			</div>
		</div>

		<div class="mt-3 text-center">
      <div class="mt-1 text-white badge text-wrap" style="text-decoration: none; font-size: 1.5rem; width: 15rem; height: 3rem; background-color: #572057 !important">
				<i class="bi bi-currency-dollar float-start"></i><%= link_to 'Financeiro', financeiro_path, class:'text-white', style:'text-decoration: none;' %>
			</div>
		</div>
		
		<div class="mt-3 text-center">
			<div class="dropdown-center">
				<a class="" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="true">
					<div class="mt-1 text-white badge text-wrap" style="text-decoration: none; font-size: 1.5rem; width: 15rem; height: 3rem; background-color: #572057 !important">
						<i class="bi bi-clipboard-data float-start"></i>Gráficos
					</div>
				</a>

				<ul class="dropdown-menu">
					<li><a class="dropdown-item" href="/relatorios/servicos">Serviços</a></li>
					<li><hr class="dropdown-divider"></li>
					<li><a class="dropdown-item" href="/relatorios/despesas">Gastos por mês</a></li>
					<li><hr class="dropdown-divider"></li>
					<li><a class="dropdown-item" href="/relatorios/lucro_mes">Lucro por mês</a></li>
				</ul>
			</div>
		</div>

		<div class="mt-3 text-center mb-5">
			 <div class="mt-1 text-white badge text-wrap" style="text-decoration: none; font-size: 1.5rem; width: 15rem; height: 3rem; background-color: #572057 !important">
				<i class="bi bi-person-add float-start"></i><%= link_to 'Usuários', new_user_path, class:'text-white', style:'text-decoration: none;' %>
			</div>
		</div>

		<% if @qnt_agendamentos_dia > 0 %>
			<div class="d-flex justify-content-center">
				<div class="card text-center shadow" style="width: 15rem;">
					<div class="card-header bg-primary text-white">
					AGENDA DO <b>DIA</b>
					</div>
					<div class="card-body ">
					<h5 class="card-title"><%= pluralize(@qnt_agendamentos_dia, 'agendamento', 'agendamentos') %></h5>
					</div>
				</div>
			</div>
		<% end %>

    <% if @qnt_agendamentos_futuros > 0 %>
      <div class="d-flex justify-content-center mt-3">
        <div class="card text-center shadow" style="width: 15rem;">
          <div class="card-header bg-primary text-white">
          AGENDA <b>FUTURA</b>
          </div>
          <div class="card-body">
          <h5 class="card-title"><%= pluralize(@qnt_agendamentos_futuros, 'agendamento', 'agendamentos') %></h5>
          </div>
        </div>
      </div>
    <% end %>

		<div class="d-flex justify-content-center mt-3">
			<div class="card text-center shadow" style="width: 15rem;">
				<div class="card-header bg-success text-white">
				VALOR DO CAIXA <b>DIÁRIO</b>
				</div>
				<div class="card-body">
				<h5 class="card-title"><%= numero_real( @valor_total_dia,2) %></h5>
				</div>
			</div>
		</div>

		<div class="d-flex justify-content-center mt-3">
			<div class="card text-center shadow" style="width: 15rem;">
				<div class="card-header bg-danger text-white">
				DESPESAS DO <b>DIA</b>
				</div>
				<div class="card-body">
				<h5 class="card-title"><%= numero_real( @despesas_do_dia ,2) %></h5>
				</div>
			</div>
		</div>

		<div class="d-flex justify-content-center mt-3">
			<div class="card text-center shadow" style="width: 15rem;">
				<div class="card-header bg-secondary text-white">
				VALOR DO LUCRO <b>TOTAL </b>
				</div>
				<div class="card-body">
				<h5 class="card-title"><%= numero_real( @valor_total_lucro,2) %></h5>
				</div>
			</div>
		</div>

		

		
		<!--<div class="mt-3 text-center">	
			<div class="badge bg-primary text-wrap" style="width: 15rem;">
				<%= link_to 'Caixa total', caixa_total_servicos_path, class:'text-white', style:'text-decoration: none' %>
			</div>
		</div>-->
	</div>