config/routes.rb
Rails.application.routes.draw do
  
  root to: "static_pages#index" #para pagina inicial
  
  resources :despesas
  
  resources :agendamentos do
    get :todos, on: :collection
    get :futuros, on: :collection
    get :json_teste, on: :collection
  end
  
  resources :servicos do
    get :caixa_total, on: :collection #usar collection pra trazer lista de dados
    get :servicos_do_dia, on: :collection
  end

  resources :relatorios do
    get :servicos, on: :collection
    get :despesas, on: :collection
    get :lucro_mes, on: :collection
  end

  get 'users/json_teste', to: 'users#json_teste'
  get '/financeiro', to: 'static_pages#financeiro'

  resources :users, only: [:new, :create, :index]

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy', as: 'sair'


  
  resources :caixas
  
  
end

app/models/servico.rb
class Servico < ApplicationRecord
validates :valor, presence: true
validates :servico, presence: true   
end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController
  before_action :require_logged_in_user#, except: [:index] 
  before_action :set_servico, only: %i[ show edit update destroy ]
  include Pagy::Backend

  # GET /servicos or /servicos.json
  def index
    @servicos = Servico.all
    
    @servicos_do_dia = Servico.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'")
    @valor_total_dia = @servicos_do_dia.map(&:valor).map(&:to_f).sum
    
    if params[:nome_search] || params[:servico_search] || params[:data_search]
      @servicos = @servicos.where('nome_cliente ILIKE ?', "%#{params[:nome_search]}%") if params[:nome_search].present?
      @servicos = @servicos.where('servico ILIKE ?', "%#{params[:servico_search]}%") if params[:servico_search].present?
      if params[:data_search].present?
        params[:data_search] = Date.parse(params[:data_search]).strftime("%Y-%m-%d")
        @servicos = @servicos.where('CAST(data AS TEXT) LIKE ?', "%#{params[:data_search]}%")
      end
    else
      @servicos = Servico.all.order(data: :desc)
    end
    
    @valor_total = @servicos.map(&:valor).map(&:to_f).sum
    @pagy, @servicos = pagy(@servicos)
  end

  def caixa_total
    @servicos = Servico.all
    @valor_total = @servicos.map(&:valor).map(&:to_f).sum
  end

  def servicos_do_dia
    @servicos_do_dia = Servico.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'")

    
    @valor_total_dia = @servicos_do_dia.map(&:valor).map(&:to_f).sum
    
    @despesas = Despesa.all
    @despesas_valor = @despesas.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'").map(&:valor_real).sum
    
    @caixa_total_dia = @valor_total_dia - @despesas_valor

    if params[:nome_search] || params[:servico_search]
      @servicos_do_dia = @servicos_do_dia.where('nome_cliente ILIKE ?', "%#{params[:nome_search]}%") if params[:nome_search].present?
      @servicos_do_dia = @servicos_do_dia.where('servico ILIKE ?', "%#{params[:servico_search]}%") if params[:servico_search].present?
    else
      @servicos_do_dia = Servico.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'").order(created_at: :desc)
    end

    @pagy, @servicos_do_dia = pagy(@servicos_do_dia)
  end

  # GET /servicos/1 or /servicos/1.json
  def show
  end

  # GET /servicos/new
  def new
    @servico = Servico.new
    
    @servicos = ["Escova Inteligente - R$100,00", "Escova Orgânica - R$100,00", 
    "Botox - R$80,00", "Hidratação - R$40,00", "Hidratação com Escova - R$60,00","Coloração - R$30,00", "Coloração com Escova - R$45,00",
    "Escova - R$25,00","Prancha - R$25,00","Escova com Prancha - R$35,00","Pé e mão - R$35,00","Mão - R$20,00","Pé - R$20,00","Spa dos pés - R$60,00",
    "Blindagem - R$50,00", "Banho de gel - R$40,00","Unhas postiças - R$40,00", "Unhas acrílico - R$100,00","Manutenção acrílico - R$80,00"]

    @servicos_prestados = []
    
    @servicos.each do |servico|
      servico_valor = servico.split
      servico_valor = servico_valor.last.gsub("R$", "").gsub(",","")

      servico = servico.gsub(/\-.+/, "")
      
      @servicos_prestados << servico
      
      if params[:servico2].present?
        @servico_valor = servico_valor if params[:servico2].gsub(/\-.+/, "") == servico
      end
      
    end
  end

  # GET /servicos/1/edit
  def edit
    @servicos = ["Escova Inteligente - R$100,00", "Escova Orgânica - R$100,00", 
    "Botox - R$80,00", "Hidratação - R$40,00", "Hidratação com Escova - R$60,00","Coloração - R$30,00", "Coloração com Escova - R$45,00",
    "Escova - R$25,00","Prancha - R$25,00","Escova com Prancha - R$35,00","Pé e mão - R$35,00","Mão - R$20,00","Pé - R$20,00","Spa dos pés - R$60,00",
    "Blindagem - R$50,00", "Banho de gel - R$40,00","Unhas postiças - R$40,00", "Unhas acrílico - R$100,00","Manutenção acrílico - R$80,00"]

    @servicos_prestados = []
    @servicos.each do |servico|
      @servicos_prestados << servico.gsub(/\-.+/, "")
    end
  end

  # POST /servicos or /servicos.json
  def create
    @servico = Servico.new(servico_params)
    @servico.valor = @servico.valor.gsub('R$','').gsub('.','').gsub(',','.').gsub(' ', '')

    @servicos = ["Escova Inteligente - R$100,00", "Escova Orgânica - R$100,00", 
    "Botox - R$80,00", "Hidratação - R$40,00", "Hidratação com Escova - R$60,00","Coloração - R$30,00", "Coloração com Escova - R$45,00",
    "Escova - R$25,00","Prancha - R$25,00","Escova com Prancha - R$35,00","Pé e mão - R$35,00","Mão - R$20,00","Pé - R$20,00","Spa dos pés - R$60,00",
    "Blindagem - R$50,00", "Banho de gel - R$40,00","Unhas postiças - R$40,00", "Unhas acrílico - R$100,00","Manutenção acrílico - R$80,00"]

    @servicos_prestados = []
    @servicos.each do |servico|
      @servicos_prestados << servico.gsub(/\-.+/, "")
    end

    if Servico.where(nome_cliente: params[:servico][:nome_cliente], servico: params[:servico][:servico]).where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'").present?
      flash[:danger] = "Serviço já cadastrado!" 
      redirect_to servicos_do_dia_servicos_path
    else
      if @servico.save
        flash[:success] = "Serviço criado com sucesso!" 
        redirect_to servicos_do_dia_servicos_path
      else
        render 'new'
      end
    end
  end

  # PATCH/PUT /servicos/1 or /servicos/1.json
  def update
    params[:servico][:valor] = params[:servico][:valor].gsub('R$','').gsub('.','').gsub(',','.').gsub(' ', '')

    @servicos = ["Escova Inteligente - R$100,00", "Escova Orgânica - R$100,00", 
    "Botox - R$80,00", "Hidratação - R$40,00", "Hidratação com Escova - R$60,00","Coloração - R$30,00", "Coloração com Escova - R$45,00",
    "Escova - R$25,00","Prancha - R$25,00","Escova com Prancha - R$35,00","Pé e mão - R$35,00","Mão - R$20,00","Pé - R$20,00","Spa dos pés - R$60,00",
    "Blindagem - R$50,00", "Banho de gel - R$40,00","Unhas postiças - R$40,00", "Unhas acrílico - R$100,00","Manutenção acrílico - R$80,00"]

    @servicos_prestados = []
    @servicos.each do |servico|
      @servicos_prestados << servico.gsub(/\-.+/, "")
    end
    
    if @servico.update(servico_params)
      flash[:success] = "Serviço atualizado com sucesso!" 
      redirect_to servicos_do_dia_servicos_path
    else
      render 'new'
    end

  end

  # DELETE /servicos/1 or /servicos/1.json
  def destroy
    @servico.destroy
    
    flash[:success] = "Serviço apagado com sucesso!" 
    redirect_to servicos_do_dia_servicos_path
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servico
      @servico = Servico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def servico_params
      params.require(:servico).permit(:data, :nome_cliente, :servico, :valor)
    end
end

app/helpers/servicos_helper.rb
module ServicosHelper
    include Pagy::Frontend
end

app/views/servicos/_form.html.erb
<%= form_with(model: servico) do |form| %>

  <%= render 'layouts/error_messages', object: form.object %>

  <div class="mb-3">
    <%= form.label :data, class:'form-label' %>
    <%= form.date_field :data, value: params[:data].present? ? params[:data] : Date.today, class:'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :nome_cliente, class:'form-label' %>
    <%= form.text_field :nome_cliente, class:'form-control text-uppercase' unless params[:nome].present? %>
    <%= form.text_field :nome_cliente, value: params[:nome], class:'form-control text-uppercase' if params[:nome].present? %>
  </div>

  <div class="mb-3">
    <%= form.label :servico, 'Serviço', class:'form-label' %>
    <%= form.select :servico, @servicos_prestados,{}, class:'form-control text-uppercase' unless params[:servico2].present? %>
    <%= form.select :servico, [params[:servico2]],{}, class:'form-control text-uppercase' if params[:servico2].present? %>
  </div>
  
  <div class="mb-3">
    <%= form.label :valor, class:'form-label' %>
    <%= form.text_field :valor, class:'form-control moeda' unless params[:servico2].present?%>
    <%= form.text_field :valor, value: @servico_valor, class:'form-control moeda' if params[:servico2].present?%>
  </div>

  <div class="mt-5">
    <%= form.submit 'Salvar', class:'btn btn-primary', style:'background-color: #572057 !important; border: none' %>
    <%= link_to "Voltar", servicos_do_dia_servicos_path, class:'btn btn-primary', style:'background-color: #572057 !important; border: none' %>
  </div>

<% end %>

<script>


 $(function() {
      $(".moeda").maskMoney({
        prefix:'R$ ',
        thousands:'.',
        decimal:','
      });
      $('#servico_valor').focus()
  });
</script>

app/views/servicos/caixa_total.html.erb
<h1>Total do caixa</h1>
<%= numero_real(@valor_total,2) %>

app/views/servicos/edit.html.erb
<h1>Editar serviço</h1>

<%= render 'form', servico: @servico %>

app/views/servicos/index.html.erb
<div class="fs-2 text-uppercase text-center mb-3">Todos os serviços</div>

<a href="/servicos/new" class="fs-1 float-end" title="Adicionar novo serviço"><i class="bi bi-plus-circle-fill color-roxo"></i></a>
<div class="d-flex justify-content-center mb-5">
  <div class="card text-center" style="width: 10rem;">
    <div class="card-header">
      Valor do caixa
      <% if  params[:nome_search].present? || params[:servico_search].present? || params[:data_search].present? %>
        <small style="font-size: 0.7rem" class="text-danger"><br>
          <b>
            <% if params[:nome_search] != '' && params[:servico_search] != '' && params[:data_search] == '' %>
              (filtro nome e serviço)
            <% elsif params[:nome_search] != '' && params[:data_search] != '' && params[:servico_search] == '' %>
              (filtro nome e data)
            <% elsif params[:nome_search] != '' && params[:servico_search] != '' && params[:data_search] != '' %>
              (filtro nome, serviço e data)
            <% elsif params[:servico_search] != '' && params[:data_search] != '' && params[:nome_search] == '' %>
              (filtro serviço e data)
            <% elsif params[:nome_search] != '' %>
              (filtro de nome)
            <% elsif params[:servico_search] != '' %>
              (filtro de serviço)
            <% elsif params[:data_search] != '' %>
              (filtro de data)
            <% end %>
          </b>
        </small>
      <% end %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= numero_real( @valor_total,2) %></h5>
    </div>
  </div>
</div>

<div>
  <form>
  <div class="row mb-4">
    <div class="col-sm-2 mb-2">
      <input type="text" name="nome_search" value="<%= params[:nome_search].present? ? params[:nome_search] : '' %>" placeholder="Buscar por nome..." class="form-control"
      onkeyup="
      var nome = this.value;
      if (nome !== null){
        this.value = nome.toUpperCase();
      }
      ">
    </div>
    <div class="col-sm-2 mb-2">
      <input type="text" name="servico_search" value="<%= params[:servico_search].present? ? params[:servico_search] : '' %>" placeholder="Buscar por serviço..." class="form-control"
      onkeyup="
      var servico = this.value;
      if (servico !== null){
        this.value = servico.toUpperCase();
      }
      ">
    </div>
    <div class="col-sm-2 mb-2">
      <input type="text" name="data_search" placeholder="Buscar por data..." value="<%= params[:data_search].present? ? Date.parse(params[:data_search]).strftime("%d/%m/%Y") : '' %>" class="form-control" 
      onkeyup="
        var v = this.value;
        if (v.match(/^\d{2}$/) !== null) {
            this.value = v + '/';
        } else if (v.match(/^\d{2}\/\d{2}$/) !== null) {
            this.value = v + '/';
        }"
        maxlength="10">
    </div>
    <div class="col-sm-4">
      <button type="submit" class="btn bg-roxo text-white ms-3">Buscar</button>
      <a href="/servicos" class="btn bg-roxo text-white ms-2">Limpar Filtro</a>
    </div>
  </div>
  </form>
</div>


<div class="p-2 mt-4 card shadow">
  <table class="table">
    <thead>
      <tr>
        <th style="width:3rem">Data</th>
        <th style="width:37rem">Nome cliente</th>
        <th style="width:15rem">Servico</th>
        <th style="width:15rem">Valor</th>
        <th>Ação</th>
        
      </tr>
    </thead>

    <tbody>
      <% @servicos.each do |servico| %>
        <tr>
          <td><div><b class="ocultar-res">Data</b> <div><%= servico.data.strftime('%d/%m/%Y') %></div></div></td>
          <td><div><b class="ocultar-res">Cliente</b> <div><%= servico.nome_cliente.upcase %></div></div></td>
          <td><div><b class="ocultar-res">Serviço</b> <div><%= servico.servico.upcase.gsub(/\-.+/, "") %></div></div></td></td>
          <td><div><b class="ocultar-res">Valor</b> <div><%= numero_real(servico.valor,2) %></div></div></td></td>
          <td>
            <%#= link_to 'Show', servico %>
            <%= link_to '', edit_servico_path(servico), class:'btn btn-primary rounded-pill bi bi-pencil-square text-white fs-6 bg-roxo' %>
            <%= link_to '', servico, method: :delete, data: { confirm: 'Deseja apagar esse serviço?' }, class: 'bg-roxo btn btn-primary rounded-pill bi bi-trash3-fill' %>
          </td>
          <td class="border-botton ocultar-res"></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<div class="div-pagy">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/servicos/new.html.erb
<h1>Novo Serviço</h1>

<%= render 'form', servico: @servico %>

app/views/servicos/servicos_do_dia.html.erb
<a href="/despesas/new" class="fs-1 float-end ms-2" title="Adicionar nova despesa"><i class="bi bi-dash-circle-fill color-roxo"></i></a>
<a href="/servicos/new" class="fs-1 float-end" title="Adicionar novo serviço"><i class="bi bi-plus-circle-fill color-roxo"></i></a>
<div class="fs-2 text-uppercase text-center mb-3">Serviços do dia</div>

<div class="d-flex justify-content-center flex-wrap mb-5">
  <div class="card text-center me-3" style="width: 10rem;">
    <div class="card-header">
      Serviços do dia
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= numero_real( @valor_total_dia,2) %></h5>
    </div>
  </div>

  <div class="card text-center me-3 " style="width: 10rem;">
    <div class="card-header text-danger">
      Valor despesa
    </div>
    <div class="card-body">
    <a href="/despesas/" class="text-black" style="text-decoration: none !important"><h5 class="card-title"><%= numero_real( @despesas_valor ,2) %></h5></a>
    </div>
  </div>

  <div class="card text-center " style="width: 10rem;">
    <div class="card-header">
      Valor do lucro
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= numero_real( @caixa_total_dia,2) %></h5>
    </div>
  </div>
</div>

<div class="mt-3">
  <form>
  <div class="row mb-4">
    <div class="col-sm-2 mb-2">
      <input type="text" name="nome_search" placeholder="Buscar por nome..." class="form-control ">
    </div>
    <div class="col-sm-2 mb-2">
      <input type="text" name="servico_search" placeholder="Buscar por serviço..." class="form-control ">
    </div>
    <div class="col-sm-4">
      <button type="submit" class="btn bg-roxo text-white ms-3">Buscar</button>
      <a href="/servicos/servicos_do_dia" class="btn bg-roxo text-white ms-2">Limpar Filtro</a>
    </div>
  </div>
  </form>
</div>

<div class="p-2 mt-4 card shadow">
  <table class="table ">
    <thead class="hide--">
      <tr>
        <th style="width:3rem">Data</th>
        <th style="width:37rem">Nome cliente</th>
        <th style="width:15rem">Servico</th>
        <th style="width:15rem">Valor</th>
        <th>Ação</th>
      </tr>
    </thead>

    <tbody>
      <% @servicos_do_dia.each do |servico| %>
        <tr>
          <td><div><b class="ocultar-res">Data</b> <div><%= servico.data.strftime('%d/%m/%Y') %></div></div></td>
          <td><div><b class="ocultar-res">Cliente</b> <div><%= servico.nome_cliente.upcase %></div></div></td>
          <td><div><b class="ocultar-res">Serviço</b> <div><%= servico.servico.gsub(/\-.+/, "").upcase %></div></div></td></td>
          <td><div><b class="ocultar-res">Valor</b> <div><%= numero_real(servico.valor,2) %></div></div></td></td>
          <td>
            <%#= link_to 'Show', servico %>
            <%= link_to '', edit_servico_path(servico), class:'btn btn-primary rounded-pill bi bi-pencil-square text-white fs-6 bg-roxo' %>
            <%= link_to '', servico, method: :delete, data: { confirm: 'Deseja apagar esse serviço?' }, class: 'bg-roxo btn btn-primary rounded-pill bi bi-trash3-fill' %>
          </td>
          <td class="border-botton ocultar-res"></td>
        </tr>
       
      <% end %>
    </tbody>
  </table>
</div>

<div class="div-pagy mt-5">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

<br>

app/views/servicos/show.html.erb
<p>
  <strong>Data:</strong>
  <%= @servico.data %>
</p>

<p>
  <strong>Nome cliente:</strong>
  <%= @servico.nome_cliente %>
</p>

<p>
  <strong>Servico:</strong>
  <%= @servico.servico %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @servico.valor %>
</p>

<%= link_to 'Edit', edit_servico_path(@servico) %> |
<%= link_to 'Back', servicos_path %>