config/routes.rb
Rails.application.routes.draw do
  
  root to: "static_pages#index" #para pagina inicial
  
  resources :despesas
  
  resources :agendamentos do
    get :todos, on: :collection
    get :futuros, on: :collection
    get :json_teste, on: :collection
  end
  
  resources :servicos do
    get :caixa_total, on: :collection #usar collection pra trazer lista de dados
    get :servicos_do_dia, on: :collection
  end

  resources :relatorios do
    get :servicos, on: :collection
    get :despesas, on: :collection
    get :lucro_mes, on: :collection
  end

  get 'users/json_teste', to: 'users#json_teste'
  get '/financeiro', to: 'static_pages#financeiro'

  resources :users, only: [:new, :create, :index]

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy', as: 'sair'


  
  resources :caixas
  
  
end

app/models/caixa.rb
class Caixa < ApplicationRecord
end

app/controllers/caixas_controller.rb
class CaixasController < ApplicationController
  before_action :require_logged_in_user
  before_action :set_caixa, only: %i[ show edit update destroy ]

  # GET /caixas or /caixas.json
  def index
    @caixas = Caixa.all
  end

  # GET /caixas/1 or /caixas/1.json
  def show
  end

  # GET /caixas/new
  def new
    @caixa = Caixa.new
  end

  # GET /caixas/1/edit
  def edit
  end

  # POST /caixas or /caixas.json
  def create
    @caixa = Caixa.new(caixa_params)

    respond_to do |format|
      if @caixa.save
        format.html { redirect_to caixa_url(@caixa), notice: "Caixa was successfully created." }
        format.json { render :show, status: :created, location: @caixa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @caixa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caixas/1 or /caixas/1.json
  def update
    respond_to do |format|
      if @caixa.update(caixa_params)
        format.html { redirect_to caixa_url(@caixa), notice: "Caixa was successfully updated." }
        format.json { render :show, status: :ok, location: @caixa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @caixa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caixas/1 or /caixas/1.json
  def destroy
    @caixa.destroy

    respond_to do |format|
      format.html { redirect_to caixas_url, notice: "Caixa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caixa
      @caixa = Caixa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def caixa_params
      params.require(:caixa).permit(:nome_cliente, :data, :valor, :servico)
    end
end

app/helpers/caixas_helper.rb
module CaixasHelper
end

app/views/caixas/_form.html.erb
<%= form_with(model: caixa) do |form| %>
  <% if caixa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caixa.errors.count, "error") %> prohibited this caixa from being saved:</h2>

      <ul>
        <% caixa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/caixas/edit.html.erb
<h1>Editing Caixa</h1>

<%= render 'form', caixa: @caixa %>

<%= link_to 'Show', @caixa %> |
<%= link_to 'Back', caixas_path %>

app/views/caixas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Caixas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caixas.each do |caixa| %>
      <tr>
        <td><%= caixa.nome %></td>
        <td><%= link_to 'Show', caixa %></td>
        <td><%= link_to 'Edit', edit_caixa_path(caixa) %></td>
        <td><%= link_to 'Destroy', caixa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caixa', new_caixa_path %>

app/views/caixas/new.html.erb
<h1>New Caixa</h1>

<%= render 'form', caixa: @caixa %>

<%= link_to 'Back', caixas_path %>

app/views/caixas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @caixa.nome %>
</p>

<%= link_to 'Edit', edit_caixa_path(@caixa) %> |
<%= link_to 'Back', caixas_path %>