config/routes.rb
Rails.application.routes.draw do
  
  root to: "static_pages#index" #para pagina inicial
  
  resources :despesas
  
  resources :agendamentos do
    get :todos, on: :collection
    get :futuros, on: :collection
    get :json_teste, on: :collection
  end
  
  resources :servicos do
    get :caixa_total, on: :collection #usar collection pra trazer lista de dados
    get :servicos_do_dia, on: :collection
  end

  resources :relatorios do
    get :servicos, on: :collection
    get :despesas, on: :collection
    get :lucro_mes, on: :collection
  end

  get 'users/json_teste', to: 'users#json_teste'
  get '/financeiro', to: 'static_pages#financeiro'

  resources :users, only: [:new, :create, :index]

  get 'entrar', to: 'sessions#new'
  post 'entrar', to: 'sessions#create'
  delete 'sair', to: 'sessions#destroy', as: 'sair'


  
  resources :caixas
  
  
end

app/models/agendamento.rb
class Agendamento < ApplicationRecord
	validates :nome, presence: true, format: { with: /\A[a-zA-Z]+\s[a-zA-Z]+\z/ } #validar nome e sobrenome
	validates :hora, presence: true
	validates :servico, presence: true
	validates :telefone, presence: true

	belongs_to :user, optional: true 

end

app/controllers/agendamentos_controller.rb
class AgendamentosController < ApplicationController
  before_action :require_logged_in_user, except: [ :new, :create, :json_teste ]
  before_action :set_agendamento, only: %i[ show edit update destroy ]
  include Pagy::Backend


  # GET /agendamentos or /agendamentos.json
  def index
    @agendamentos = Agendamento.all
    
    if params[:nome_search] || params[:servico_search]
      @agendamentos_dia = @agendamentos.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'").where('nome ILIKE ?', "%#{params[:nome_search]}%").sort_by { |obj| obj.hora.to_i } if params[:nome_search].present?
      @agendamentos_dia = @agendamentos.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'").where('servico ILIKE ?', "%#{params[:servico_search]}%").sort_by { |obj| obj.hora.to_i } if params[:servico_search].present?    
    else
      @agendamentos_dia = @agendamentos.where("to_char(data,'YYYY-MM-DD') = '#{Time.now.to_date.to_s}'").sort_by { |obj| obj.hora.to_i }
    end
    
    @qnt_agendamentos = @agendamentos_dia.count

    @qnt_agendamentos_futuros = @agendamentos.where("to_char(data,'YYYY-MM-DD') > '#{Time.now.to_date.to_s}'").count

    @servico = Servico.all
  end

  def todos
    @agendamentos = Agendamento.all.order(data: :desc)
    
    if params[:nome_search] || params[:servico_search] || params[:data_search]
      @agendamentos = @agendamentos.where('nome ILIKE ?', "%#{params[:nome_search]}%") if params[:nome_search].present?
      @agendamentos = @agendamentos.where('servico ILIKE ?', "%#{params[:servico_search]}%") if params[:servico_search].present?
      if params[:data_search].present?
        params[:data_search] = Date.parse(params[:data_search]).strftime("%Y-%m-%d")
        @agendamentos = @agendamentos.where('CAST(data AS TEXT) LIKE ?', "%#{params[:data_search]}%")
      end
    else
      @agendamentos = Agendamento.all.order(data: :desc)
    end

    @pagy, @agendamentos = pagy(@agendamentos)
  end

  def futuros
    @agendamentos = Agendamento.where("to_char(data,'YYYY-MM-DD') > '#{Time.now.to_date.to_s}'").order(:data)

    if params[:nome_search] || params[:servico_search] || params[:data_search]
      @agendamentos = @agendamentos.where('nome ILIKE ?', "%#{params[:nome_search]}%") if params[:nome_search].present?
      @agendamentos = @agendamentos.where('servico ILIKE ?', "%#{params[:servico_search]}%") if params[:servico_search].present?
      if params[:data_search].present?
        params[:data_search] = Date.parse(params[:data_search]).strftime("%Y-%m-%d")
        @agendamentos = @agendamentos.where('CAST(data AS TEXT) LIKE ?', "%#{params[:data_search]}%")
      end
    else
      @agendamentos = Agendamento.where("to_char(data,'YYYY-MM-DD') > '#{Time.now.to_date.to_s}'").order(:data)
    end

    @pagy, @agendamentos = pagy(@agendamentos)
  end

  def json_teste   
    @agendamentos = Agendamento.where(data: params[:data])
    render json: JSON.parse(@agendamentos.to_json)
  end

  # GET /agendamentos/1 or /agendamentos/1.json
  def show
  end

  # GET /agendamentos/new
  def new
    @agendamento = Agendamento.new
    @servicos = ["Escova Inteligente - R$100,00", "Escova Orgânica - R$100,00", 
    "Botox - R$80,00", "Hidratação - R$40,00", "Hidratação com Escova - R$60,00","Coloração - R$30,00", "Coloração com Escova - R$45,00",
    "Escova - R$25,00","Prancha - R$25,00","Escova com Prancha - R$35,00","Pé e mão - R$35,00","Mão - R$20,00","Pé - R$20,00","Spa dos pés - R$60,00",
    "Blindagem - R$50,00", "Banho de gel - R$40,00","Unhas postiças - R$40,00", "Unhas acrílico - R$100,00","Manutenção acrílico - R$80,00"]
  end

  # GET /agendamentos/1/edit
  def edit
     @servicos = ["Escova Inteligente - R$100,00", "Escova Orgânica - R$100,00", 
    "Botox - R$80,00", "Hidratação - R$40,00", "Hidratação com Escova - R$60,00","Coloração - R$30,00", "Coloração com Escova - R$45,00",
    "Escova - R$25,00","Prancha - R$25,00","Escova com Prancha - R$35,00","Pé e mão - R$35,00","Mão - R$20,00","Pé - R$20,00","Spa dos pés - R$60,00",
    "Blindagem - R$50,00", "Banho de gel - R$40,00","Unhas postiças - R$40,00", "Unhas acrílico - R$100,00","Manutenção acrílico - R$80,00"]
    
  end

  # POST /agendamentos or /agendamentos.json
  def create
    if current_user
      @agendamento = current_user.agendamentos.build(agendamento_params)
      @agendamento.telefone = @agendamento.telefone.gsub('(','').gsub(')','').gsub(' ','').gsub('-','')
    else
      params[:agendamento][:telefone] = params[:agendamento][:telefone].gsub('(','').gsub(')','').gsub(' ','').gsub('-','')
      @agendamento = Agendamento.new(agendamento_params)
    end

    @servicos = ["Escova Inteligente - R$100,00", "Escova Orgânica - R$100,00", 
    "Botox - R$80,00", "Hidratação - R$40,00", "Hidratação com Escova - R$60,00","Coloração - R$30,00", "Coloração com Escova - R$45,00",
    "Escova - R$25,00","Prancha - R$25,00","Escova com Prancha - R$35,00","Pé e mão - R$35,00","Mão - R$20,00","Pé - R$20,00","Spa dos pés - R$60,00",
    "Blindagem - R$50,00", "Banho de gel - R$40,00","Unhas postiças - R$40,00", "Unhas acrílico - R$100,00","Manutenção acrílico - R$80,00"]
    
    if Agendamento.where(hora: params[:agendamento][:hora]).where(data: params[:agendamento][:data]).present?
      flash[:danger] = "Horário indisponível."
      redirect_to new_agendamento_path
    elsif params[:agendamento][:hora] == "Sem hora dispónivel"
      flash[:danger] = "Sem hora dispónivel para o dia selecionado."
      render 'new'
    else
      if @agendamento.save
        flash[:success] = "Agendamento criado com sucesso!"
        redirect_to new_agendamento_path
      else
        render 'new'
      end
    end
  end
    
    

  # PATCH/PUT /agendamentos/1 or /agendamentos/1.json
  def update
    @agendamento.telefone = @agendamento.telefone.gsub('(','').gsub(')','').gsub(' ','').gsub('-','')
    
    @servicos = ["Escova Inteligente - R$100,00", "Escova Orgânica - R$100,00", 
    "Botox - R$80,00", "Hidratação - R$40,00", "Hidratação com Escova - R$60,00","Coloração - R$30,00", "Coloração com Escova - R$45,00",
    "Escova - R$25,00","Prancha - R$25,00","Escova com Prancha - R$35,00","Pé e mão - R$35,00","Mão - R$20,00","Pé - R$20,00","Spa dos pés - R$60,00",
    "Blindagem - R$50,00", "Banho de gel - R$40,00","Unhas postiças - R$40,00", "Unhas acrílico - R$100,00","Manutenção acrílico - R$80,00"]
    
    if @agendamento.update(agendamento_params)
      flash[:success] = "Agendamento editado com sucesso!" 
      redirect_to agendamentos_path
    else
      render 'new'
    end
    
  end

  # DELETE /agendamentos/1 or /agendamentos/1.json
  def destroy
    @agendamento.destroy
    flash[:success] = "Agendamento apagado com sucesso!" 
    redirect_to agendamentos_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agendamento
      @agendamento = Agendamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agendamento_params
      params.require(:agendamento).permit(:data, :hora, :nome, :servico, :telefone)
    end
end

app/helpers/agendamentos_helper.rb
module AgendamentosHelper
    include Pagy::Frontend

    def maiusculo(nome)
		nome_array = nome.split(" ")
		upper = nome_array.map(&:capitalize)
		upper_all = upper.join(" ")
		upper_all
	end
end

app/views/agendamentos/_form.html.erb
  <%= form_with(model: agendamento) do |form| %>

    <div class="mb-3">
      <%= form.label :data, class:'form-label' %>

      <%= form.date_field :data, value: params[:agendamento].present? ? params[:agendamento][:data] : Date.today , class:'form-control' %>
    </div>

    <div class="mb-3">
      <%= form.label :hora, 'Horários disponíveis', class:'form-label' %>
      <%= form.select :hora, [["9h"],["11h"],["13h"],["15h"],["17h"]],{}, class:'form-control' %>
    </div>

    <div class="mb-3">
    <% if @agendamento.errors.has_key?(:nome) %>
      <div class="error_message float-end" id="msg-nome-agendamento2">Nome e sobrenome obrigatório</div>
    <% end %>
      <div class="error_message float-end" id="msg-nome-agendamento">Nome e sobrenome obrigatório</div>
      <%= form.label :nome, class:'form-label' %>
      <%= form.text_field :nome, class:"form-control moeda text-uppercase" %>

    </div>

    <div class="mb-3">
      <div class="error_message float-end" id="msg-telefone-agendamento">Telefone inválido</div>
      <% if @agendamento.errors.has_key?(:telefone) %>
        <div class="error_message float-end" id="error_msg">Obrigatório</div>
      <% end %>
      <%= form.label :telefone, class:'form-label' %>

      <% if @agendamento.errors.has_key?(:telefone) %>
        <%= form.text_field :telefone, class:'form-control moeda aviso', onkeypress:"$(this).mask('(00) 00000-0000')" %>
      <% else %>
        <%= form.text_field :telefone, class:'form-control moeda', onkeypress:"$(this).mask('(00) 00000-0000')" %>
      <% end %>
    
    </div>

    <div class="mb-3">
      <% if @agendamento.errors.has_key?(:servico) %>
        <div class="error_message float-end" id="error_msg2">Selecione um serviço</div>
      <% end %>
      <%= form.label :servico, 'Serviço', class:'form-label' %>
      <%= form.select :servico, @servicos, {:include_blank => "Selecione o serviço"}, class:'form-control text-uppercase' %>
    </div>
    

    <div class="mt-5">
      <%= form.submit 'Salvar', class:'btn btn-primary', style:'background-color: #572057 !important; border: none' %>
      <%#= link_to "Voltar", _path, class:'btn btn-primary' %>
    </div>
  <% end %>

<script>
$('#agendamento_telefone').mask('(00) 00000-0000')
</script>

<script>
$('#msg-nome-agendamento').hide()
$('#msg-telefone-agendamento').hide()
  const nameField = document.querySelector('#agendamento_nome');
  const telefone = document.querySelector('#agendamento_telefone');
  const servico = document.querySelector('#agendamento_servico');
  const nameError = document.querySelector('.error_message');
  const nameError1 = document.querySelector('#error_msg');
  const nameError2 = document.querySelector('#error_msg2');
  const padrao = /^((\b[A-zÀ-ú']{2,40}\b)\s*){2,}$/; //regex para nome e sobrenome(3 caracteres)

  nameField.addEventListener('keyup', () => {
    if (nameField.value !== '' && padrao.test(nameField.value) ) {
      //nameError.style.display = 'none';
      $('#msg-nome-agendamento2').hide()
      $('#msg-nome-agendamento').hide()
      nameField.classList.remove ("aviso")
    } else {
      $('#msg-nome-agendamento2').hide()
      $('#msg-nome-agendamento').show()
      //nameError.style.display = 'block';
      nameField.classList.add ("aviso")
    }
  });

   telefone.addEventListener('keyup', () => {
    if (telefone.value.trim() !== '' && telefone.value.length == 15) {
      $('#msg-telefone-agendamento').hide()
      telefone.classList.remove ("aviso")
    } else {
      $('#msg-telefone-agendamento').show()
      $('#error_msg').hide()
      telefone.classList.add ("aviso")
    }
  });

 
  servico.addEventListener('input', () => {
    if (servico.value.trim() !== '') {
      nameError2.style.display = 'none';
      servico.classList.remove ("aviso")
    } else {
      nameError2.style.display = 'block';
      servico.classList.add ("aviso")
    }
  });
</script>

<% unless params[:action] == 'edit' %>
  <script>

  $('#agendamento_data').change(function() {
    
    fetch("/agendamentos/json_teste?data="+ $('#agendamento_data').val())
    .then( response => response.json())
    .then( json => {

      var htmlOptions = ""
      
  //debugger

      if(json.length >= 1){
        $("#agendamento_hora").empty();
        array = ["9h","11h","13h","15h","17h"]
        for (i = 0; i < array.length; i++) {
          $('#agendamento_hora').append('<option>' + array[i] + '</option>');
        }
        for (var i = 0; i<json.length; i++){
          $('#agendamento_hora option').each(function() {
            if ( $(this).val() == json[i]['hora'] ) {
            $(this).remove();
            }
          });
        }
          var x = $('#agendamento_hora').val()
          if ((x == "")||(x == null)) {
          $('#agendamento_hora').append('<option>Sem hora dispónivel</option>');
          return false;
          };
      }else{
        $("#agendamento_hora").empty();
        array = ["9h","11h","13h","15h","17h"]
        for (i = 0; i < array.length; i++) {
          $('#agendamento_hora').append('<option>' + array[i] + '</option>');
        }
      }

  });

  })

  $('#agendamento_data').ready(function() {
    
    fetch("/agendamentos/json_teste?data="+ $('#agendamento_data').val())
    .then( response => response.json())
    .then( json => {

      var htmlOptions = ""
      
  //debugger

      if(json.length >= 1){
        $("#agendamento_hora").empty();
        array = ["9h","11h","13h","15h","17h"]
        for (i = 0; i < array.length; i++) {
          $('#agendamento_hora').append('<option>' + array[i] + '</option>');
        }
        for (var i = 0; i<json.length; i++){
          $('#agendamento_hora option').each(function() {
            if ( $(this).val() == json[i]['hora'] ) {
            $(this).remove();
            }
          });
        }
          var x = $('#agendamento_hora').val()
          if ((x == "")||(x == null)) {
          $('#agendamento_hora').append('<option>Sem hora dispónivel</option>');
          return false;
          };
      }else{
        $("#agendamento_hora").empty();
        array = ["9h","11h","13h","15h","17h"]
        for (i = 0; i < array.length; i++) {
          $('#agendamento_hora').append('<option>' + array[i] + '</option>');
        }
      }


  });

  })
  </script>
<% end %>

app/views/agendamentos/edit.html.erb
<h1>Editar Agendamento</h1>

<%= render 'form', agendamento: @agendamento %>

app/views/agendamentos/futuros.html.erb
<h3 class="mt-2 mb-5">AGENDAMENTOS FUTUROS</h3>

<div>
  <form>
  <div class="row mb-4">
    <div class="col-sm-2 mb-2">
      <input type="text" name="nome_search" value="<%= params[:nome_search].present? ? params[:nome_search] : '' %>" placeholder="Buscar por nome..." class="form-control"
      onkeyup="
      var nome = this.value;
      if (nome !== null){
        this.value = nome.toUpperCase();
      }
      ">
    </div>
    <div class="col-sm-2 mb-2">
      <input type="text" name="servico_search" value="<%= params[:servico_search].present? ? params[:servico_search] : '' %>" placeholder="Buscar por serviço..." class="form-control"
      onkeyup="
      var servico = this.value;
      if (servico !== null){
        this.value = servico.toUpperCase();
      }
      ">
    </div>
    <div class="col-sm-2 mb-2">
      <input type="text" name="data_search" placeholder="Buscar por data..." value="<%= params[:data_search].present? ? Date.parse(params[:data_search]).strftime("%d/%m/%Y") : '' %>" class="form-control" 
      onkeyup="
        var v = this.value;
        if (v.match(/^\d{2}$/) !== null) {
            this.value = v + '/';
        } else if (v.match(/^\d{2}\/\d{2}$/) !== null) {
            this.value = v + '/';
        }"
        maxlength="10">
    </div>
    <div class="col-sm-4">
      <button type="submit" class="btn bg-roxo text-white ms-3">Buscar</button>
      <a href="/agendamentos/futuros" class="btn bg-roxo text-white ms-2">Limpar Filtro</a>
    </div>
  </div>
  </form>
</div>

<div class="card shadow p-2 mt-4">
  <table class="table">
    <thead>
      <tr>
        <th style="width:3rem">Data</th>
        <th>Hora</th>
        <th>Nome</th>
        <th>Telefone</th>
        <th>Serviço</th>
        <th>Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @agendamentos.each do |agendamento| %>
        <tr>
          <td><div><b class="ocultar-res">Data</b> <div><%= agendamento.data.strftime('%d/%m/%Y') %></div></div></td>
          <td><div><b class="ocultar-res">Hora</b> <div><%= agendamento.hora %></div></div></td>
          <td><div><b class="ocultar-res">Cliente</b> <div><%= agendamento.nome.upcase %></div></div></td>
          <td><div><b class="ocultar-res">Telefone</b> <div><span class="telefone"><%= agendamento.telefone %></span>
            <a href="https://wa.me/55<%= agendamento.telefone %>" target="_blank" class="badge rounded-pill bg-success" title="Abrir whatsapp do cliente">
              <i class="bi bi-whatsapp text-white"></i>
            </a>
            </div></div>
          </td>
          <td><div><b class="ocultar-res">Serviço</b> <div><%= agendamento.servico.upcase %></div></div></td>
          <td>
            <%#= link_to 'Show', agendamento %>
            <%= link_to '', edit_agendamento_path(agendamento), class: 'btn btn-primary rounded-pill bi bi-pencil-square text-white fs-6 bg-roxo'  %>
            <%= link_to '', agendamento, method: :delete, class: 'btn btn-primary rounded-pill bi bi-trash3-fill bg-roxo', data: { confirm: 'Are you sure?' } %>
          </td>
          <td class="border-botton ocultar-res"></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="div-pagy mt-4">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

<script>
  $('.telefone').mask('(00) 00000-0000')
</script>

<%= link_to 'Voltar', agendamentos_path, class: 'btn btn-primary mt-4 bg-roxo'  %>

app/views/agendamentos/index.html.erb
<a href="/agendamentos/new" class="fs-1 float-end color-roxo" title="Adicionar novo agendamento"><i class="bi bi-plus-circle-fill"></i></a>
<a href="/agendamentos/futuros" class="fs-1 float-end me-2 color-roxo" title="Mostrar agendamentos futuros"><i class="bi bi-fast-forward-circle-fill"></i></a>
<a href="/agendamentos/todos" class="fs-1 float-end me-2 color-roxo" title="Mostrar todos os agendamentos"><i class="bi bi-filter-circle-fill"></i></a>
<h3 class="mt-2 mb-5">AGENDAMENTOS DO DIA</h3>

<div>
  <form>
  <div class="row mb-4">
    <div class="col-sm-2 mb-2">
      <input type="text" name="nome_search" placeholder="Buscar por nome..." class="form-control ">
    </div>
    <div class="col-sm-2 mb-2">
      <input type="text" name="servico_search" placeholder="Buscar por serviço..." class="form-control ">
    </div>
    <div class="col-sm-4 mb-2">
      <button type="submit" class="btn bg-roxo text-white ms-3">Buscar</button>
      <a href="/agendamentos" class="btn bg-roxo text-white ms-2">Limpar Filtro</a>
    </div>
  </div>
  </form>
</div>

<% if @qnt_agendamentos >= 1 %>
  <div>Você tem <b class="color-roxo"><%= pluralize(@qnt_agendamentos, 'serviço agendado', 'serviços agendados') %></b> hoje.</div>
<% else %>
  <div>Você ainda não tem serviços agendados hoje.</div>
<% end %>

<% unless @agendamentos_dia.empty? %>
  <div class="p-2 mt-4 card shadow">
    <table class="table ">
      <thead>
        <tr>
          <th style="width:3rem">Data</th>
          <th>Hora</th>
          <th>Nome</th>
          <th>Telefone</th>
          <th>Serviço</th>
          <th>Ações</th>
        </tr>
      </thead>

      <tbody class="">
        <% @agendamentos_dia.each do |agendamento| %>
          <tr>
            <td><div><b class="ocultar-res">Data</b> <div><%= agendamento.data.strftime('%d/%m/%Y') %></div></div></td>
            <td><div><b class="ocultar-res">Hora</b> <div><%= agendamento.hora %></div></div></td>
            <td><div><b class="ocultar-res">Cliente</b> <div><%= agendamento.nome.upcase %></div></div></td>
            <td><div><b class="ocultar-res">Telefone</b> <div><span class="telefone"><%= agendamento.telefone %></span>
              <a href="https://wa.me/55<%= agendamento.telefone %>" target="_blank" class="badge rounded-pill bg-success" title="Abrir whatsapp do cliente">
                <i class="bi bi-whatsapp text-white"></i>
              </a>
              </div></div>
            </td>
            <td><div><b class="ocultar-res">Serviço</b> <div><%= agendamento.servico&.upcase.gsub(/\-.+/, "") %></div></div></td>
            <td>
              <%#= link_to 'Show', agendamento %>
              <%= link_to '', new_servico_path(servico2: agendamento.servico, nome: agendamento.nome.upcase, data: agendamento.data), class: 'btn btn-primary rounded-pill bi bi-wallet2 text-white fs-6 bg-roxo'  %>
              <%= link_to '', edit_agendamento_path(agendamento), class: 'btn btn-primary rounded-pill bi bi-pencil-square text-white fs-6 bg-roxo'  %>
              <%= link_to '', agendamento, method: :delete, class: 'btn btn-primary rounded-pill bi bi-trash3-fill bg-roxo', data: { confirm: 'Vai apagar?' } %>
            </td>
            <td class="border-botton ocultar-res"></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="p-2 mt-4 card shadow">
    <table class="table">
      <thead>
        <tr>
          <th style="width:3rem">Data</th>
          <th>Hora</th>
          <th>Nome</th>
          <th>Telefone</th>
          <th>Serviço</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td colspan=12>
            <% if params[:nome_search].present? %>
              <b>Nome não encontrado</b>
            <% else %>
              <b>Serviço não encontrado</b>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
<% end %>

<div class="mt-4">
  <% if @qnt_agendamentos_futuros >= 1 %>
    <a href="/agendamentos/futuros" style="text-decoration: none" class="text-black"><div>Você tem <b class="color-roxo"><%= pluralize(@qnt_agendamentos_futuros, 'serviço agendado', 'serviços agendados') %></b> futuro.</div></a>
  <% end %>
</div>

<script>
$('.telefone').mask('(00) 00000-0000')
</script>

app/views/agendamentos/todos.html.erb
<h3 class="mt-2 mb-5">TODOS AGENDAMENTOS</h3>

<div>
  <form>
  <div class="row mb-4">
    <div class="col-sm-2 mb-2">
      <input type="text" name="nome_search" value="<%= params[:nome_search].present? ? params[:nome_search] : '' %>" placeholder="Buscar por nome..." class="form-control"
      onkeyup="
      var nome = this.value;
      if (nome !== null){
        this.value = nome.toUpperCase();
      }
      ">
    </div>
    <div class="col-sm-2 mb-2">
      <input type="text" name="servico_search" value="<%= params[:servico_search].present? ? params[:servico_search] : '' %>" placeholder="Buscar por serviço..." class="form-control"
      onkeyup="
      var servico = this.value;
      if (servico !== null){
        this.value = servico.toUpperCase();
      }
      ">
    </div>
    <div class="col-sm-2 mb-2">
      <input type="text" name="data_search" placeholder="Buscar por data..." value="<%= params[:data_search].present? ? Date.parse(params[:data_search]).strftime("%d/%m/%Y") : '' %>" class="form-control" 
      onkeyup="
        var v = this.value;
        if (v.match(/^\d{2}$/) !== null) {
            this.value = v + '/';
        } else if (v.match(/^\d{2}\/\d{2}$/) !== null) {
            this.value = v + '/';
        }"
        maxlength="10">
    </div>
    <div class="col-sm-4">
      <button type="submit" class="btn bg-roxo text-white ms-3">Buscar</button>
      <a href="/agendamentos/todos" class="btn bg-roxo text-white ms-2">Limpar Filtro</a>
    </div>
  </div>
  </form>
</div>

<div class="card shadow p-2 mt-4 mb-3">
  <table class="table">
    <thead>
      <tr>
        <th style="width:3rem">Data</th>
        <th>Hora</th>
        <th>Nome</th>
        <th>Telefone</th>
        <th>Serviço</th>
        <th>Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @agendamentos.each do |agendamento| %>
        <tr>
          <td><div><b class="ocultar-res">Data</b> <div><%= agendamento.data.strftime('%d/%m/%Y') %></div></div></td>
          <td><div><b class="ocultar-res">Hora</b> <div><%= agendamento.hora %></div></div></td>
          <td><div><b class="ocultar-res">Cliente</b> <div><%= agendamento.nome.upcase %></div></div></td>
          <td><div><b class="ocultar-res">Telefone</b> <div><span class="telefone"><%= agendamento.telefone %></span>
            <a href="https://wa.me/55<%= agendamento.telefone %>" target="_blank" class="badge rounded-pill bg-success" title="Abrir whatsapp do cliente">
              <i class="bi bi-whatsapp text-white"></i>
            </a>
            </div></div>
          </td>
          <td><div><b class="ocultar-res">Serviço</b> <div><%= agendamento.servico.upcase %></div></div></td>
          <td>
            <%#= link_to 'Show', agendamento %>
            <%#= link_to '', edit_agendamento_path(agendamento), class: 'btn btn-primary rounded-pill bi bi-pencil-square text-white fs-6 bg-roxo'  %>
            <%= link_to '', agendamento, method: :delete, class: 'btn btn-primary rounded-pill bi bi-trash3-fill bg-roxo', data: { confirm: 'Are you sure?' } %>
          </td>
          <td class="border-botton ocultar-res"></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>
<%== pagy_bootstrap_nav(@pagy) %>
  <%= link_to 'Voltar', agendamentos_path, class: 'btn btn-primary mt-4 bg-roxo'  %>



<script>
$('.telefone').mask('(00) 00000-0000')
</script>